# Generated by Django 5.2.8 on 2026-06-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmetrics',
            name='horizon_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modelmetrics',
            name='trained_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='modelmetrics',
            index=models.Index(fields=['ticker', 'horizon_days'], name='main_modelm_ticker_366fab_idx'),
        ),
    ]
